port=80
urlscheme=http
curlflag=
domain=
root=
startdate="`date +"%d-%m-%Y %H:%M:%S"`"
dir=
# wordlist="/usr/share/wordlists/wfuzz/general/megabeast.txt"
wordlist="/usr/share/wordlists/wfuzz/general/big.txt"
bburp=true
